### ISSUE TITLE
Conflicting documentation about pyproject configuration for the news fragments directory

### ISSUE THREAD

**Issue by exarkun** [twisted/towncrier#109]
http://towncrier.readthedocs.io/en/actual-freaking-docs/configuration.html says `fragment_directory`
Experimentation and reading the source suggests `directory` is the necessary item.

**Comment by dklimpel** [comment]
IMO this is fixed

**Comment by adiroiban** [comment]
Thanks for the followup.

The documentation is now hosted at https://towncrier.readthedocs.io/en/stable/configuration.html#top-level-keys

`directory` is the first documented item.

I will close this.

If you think that this is not yet fixed, please let me know and we can reopen it.
