### ISSUE TITLE
Conflicting documentation about pyproject configuration for configuring the start_line

### ISSUE THREAD

**Issue by exarkun** [twisted/towncrier#110]
http://towncrier.readthedocs.io/en/actual-freaking-docs/configuration.html says to put "start_line" item in to pyproject.toml

The implementation ignores this and uses "start_string" instead.

**Comment by Ch3LL** [comment]
i ran into this issue as well. I noticed it has `start_line` in the README.rst as well. I'm more than willing to either update the docs or the code to reflect what it should be. Should it be `start_line` or `start_string`?

**Comment by ValentinCalomme** [comment]
Modifying the documentation would cause fewer issues than changing the code. If you change the code, everyone using the package who figured out they should use `start_string` will see their documentation be messed up. Or, you could create an alias such that both `start_string` and `start_line` work. Although, it is usually best to keep the config file neat to avoid confusion.

I would actually propose to name this setting `start_after`. I feel that `start_line` or `start_string` could be understood as "my changelog will start with this particular line or string", which isn't accurate.

**Comment by SmileyChris** [comment]
The documentation for this in the configuration reference was updated some time ago.

A well documented setting is probably more important that changing the name, so let's stick with what we have
