### ISSUE TITLE
Skip ticket id from the news fragments

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#14]
Some categories don't need to have a reference to the ticket id

for example, in my use case, only bugfixes have an ID to support case / KB article which discuss the error

For new features or deprecated feature the internal dev id for ticket are not helpful to end users 

I would say that for the start there can be a simple flag which disable the ID for all news fragments.

For our case the support case ID would be different than the dev ticket id and it ca be inserted as the content of the fragment.

We also use the dev id for bugs... as a shortcut

**Comment by altendky** [comment]
I guess this would be good as a configurable per-type setting?  `show_id=True` or whatever?

**Comment by adiroiban** [comment]
I think that this can be closed. 

I think that when you define the category in the toml config (https://github.com/twisted/towncrier/blob/master/README.rst#further-options) similar to `showcontent` we can have `show_refefernce_id` or something like that.

And then do extra formatting in Jinja.

**Comment by SmileyChris** [comment]
We have got non-issue fragments (orphans) now.
