### ISSUE TITLE
Running check after building the changelog

### ISSUE THREAD

**Issue by energizah** [twisted/towncrier#152]
I'm admittedly still figuring out the workflow for towncrier. 

I'm trying something like:

```bash
# Checkout the new feature branch.
git checkout -b newbranch 
# Make a change.
echo 'def f(): ...' >> pkg/__init__.py   
# Commit the change.
git commit -am'Add __init__.py'
# Add the newsfragment
echo 'Make pkg into a package.' > changelog.d/123.change
# Bump the version number
bump2version patch
# Check for newsfragments
python -m towncrier.check
# Update changelog
towncrier --yes
# Ready to go? Let's double check everything.
# Run `tox -e check` which includes...
python -m towncrier.check
# which fails.
```
This last step fails because I've already updated the changelog and removed the fragments.  Could `towncrier.check` figure out that it's already handled the newsfragments for this branch?

**Comment by altendky** [comment]
@energizah, are you satisfied that the other issues and PR cover this?  In other words, is closing as duplicate appropriate?

**Comment by energizah** [comment]
> This last step fails because I've already updated the changelog and removed the fragments

which is both the input files and the output files. But the PR only [mentions](https://github.com/twisted/towncrier/pull/174/files#diff-39e848315d21039d8a0fdffa1dbab10482acbf291ad180645e17e8f44845dbb0) the output files:

> not fail when a pull request only modifies the configured news file

**Comment by altendky** [comment]
I think the 'only' refers to not requiring that you have a new newsfragment, which is the normal thing being checked presently.  I don't think there's any checking to make sure you have not removed newsfragments.  Presently towncrier check works for feature/bugfix/etc PRs.  My expectation is that the PR would make it also able to handle release PRs where towncrier has been called and consumed the newsfragments and updated the changelog.  Do these expectations cover your needs?  Maybe I should have been thinking of #246 as the duplicate but...  anyways, forget closing this.  Just make sure I am trying to achieve what you need.

**Comment by energizah** [comment]
> Do these expectations cover your needs?

I think so. For concreteness, my scenario has an MWE in the OP.

**Comment by adiroiban** [comment]
I would say that the current behavior  is expected.

`--check` is checking if you can build a valid NEWS / Release file.

If you have just generated the file... you can't generate it again, so `--check` should fail.

From the description on this issue, it looks like you are trying to use `--check` for **post** release checks...but my understand is that check is designed for **pre** release checks.

Maybe rename `--check` to `--check-pre-release`   ... and later we can add `--check-release`

**Comment by adiroiban** [comment]
To fix this issue, I think that we should start by documenting the `--check` command.
I don't see anything about it inside README or `towncrier --help`.

**Comment by energizah** [comment]
Instead of renaming `--check` to indicate _when_ you're supposed to run it (`--check-pre-release`), it's at least worth considering a name that says _what_ it checks.
