### ISSUE TITLE
Please document what `towncrier.check` check for and how to use it

### ISSUE THREAD

**Issue by htgoebel** [twisted/towncrier#154]
The README does not state anything about `towncrier.check`. [NEWS.rst](https://github.com/hawkowl/towncrier/blob/master/NEWS.rst#towncrier-1860-2018-07-05) says:
> Features:
> * `python -m towncrier.check`, which will check a Git branch for the presence of added newsfiles […]

Please add a few lines of documentation:
What exactly does `towncrier.check` check for? What is its intended usage?

**Comment by achimnol** [comment]
I just found that `towncrier.check` only checks the existence of new fragments, not their numberings with the current PR number or other IDs. It would be nice to have a configuration to specify the environment variable name and/or pattern to extract and compare the IDs from the file names of fragments with the ID from the CI environment.

**Comment by altendky** [comment]
@achimnol, thanks for the suggestion.  That sounds like a feature request deserving of its own issue in addition to the mention here?  It sort of plays into the discussion in #309 as well, so reference that, but at the moment I think a dedicated ticket would be good.
