### ISSUE TITLE
Create a (or pick an existing) GitHub org, move towncrier to it, and grant more developers access

### ISSUE THREAD

**Issue by exarkun** [twisted/towncrier#159]
Lots of people want to use and contribute to towncrier.  Enable this by making the towncrier development community inclusive by default instead of exclusive by default.

**Comment by omry** [comment]
I think this is a good idea.
Towncrier feels very useful, but is lacking in many ways.
a few examples off the top of my head:

1. Support GitHub markdown output
2. Support callback for getting current project version (This can make towncrier a standard tool for projects in other languages as well and also make things more flexible for Python projects).

**Comment by tjanez** [comment]
I second this idea.

I've submitted [3 pull requests (from Dec 19, 2019 to Jan 9, 2020)](https://github.com/hawkowl/towncrier/pulls/tjanez) and none received a maintainer comment/review/... yet.

Note that I don't want to blame anyone and I know this is open source. Perhaps adding more maintainers or moving to an organization would help share the burden and make towncrier a healthier project for the future.

/cc @hawkowl

**Comment by hawkowl** [comment]
Towncrier has been moved to the Twisted organisation.
