### ISSUE TITLE
Towncrier incarnation with `python -mtowncrier` fails

### ISSUE THREAD

**Issue by seberg** [twisted/towncrier#163]
On current master, running towncrier with `python -mtowncrier` fails with `_main()` not being found. This probably is not an issue for me right now, since I can just call the script which works fine.

**Comment by altendky** [comment]
It looks like this was fixed in #170 and released in 19.9.0rc1 (though we have no tag for that in this repo...).  @seberg, are you comfortable closing this?

**Comment by seberg** [comment]
Thanks!
