### ISSUE TITLE
Setting title_format = false does not work

### ISSUE THREAD

**Issue by vytas7** [twisted/towncrier#164]
Hello,
I would like to disable title generation as our file already has a title heading.

`README.rst` mentions this can be achieved by setting `title_format` to `false` in the `pyproject.toml` config:
```toml
    title_format = "{name} {version} ({project_date})"  # or false if template includes title
```

However, that doesn't quite work for me:
```
...

  File "<... my virtual env ...>/lib/python3.7/site-packages/towncrier/__init__.py", line 122, in __main
    top_line = config["title_format"].format(
AttributeError: 'bool' object has no attribute 'format'
```

Setting `title_format` to an empty string seems to work (?) as a workaround, although a lot of empty space is emitted suggesting it is sort of using that string to format a zero-length heading.

**Comment by altendky** [comment]
@vytas7, I think this has been fixed though there seemed to be no tests for it.  I added a couple in #299 (and snuck in one less newline which seemed more consistent).  Would you be willing to take a look at that and/or try out the `master` branch to see if your issue is still present?

**Comment by vytas7** [comment]
Thanks for looking into this @altendky !
Checking master and your feature branch.

**Comment by vytas7** [comment]
`towncrier==19.9.0rc1` already works as expected (`false` is honoured).
Now it's just a matter of getting a stable release out :slightly_smiling_face: 

(FWIW, using the branch from your PR did not render any difference in our case.)
