### ISSUE TITLE
Switch from Trial to pytest?

### ISSUE THREAD

**Issue by nedbat** [twisted/towncrier#171]
I don't know if there's any interest in doing this.  Trial is a pretty niche test runner at this point. It's the only reason towncrier is installing Twisted.

Would switching to pytest be welcomed, or abhorred, or meh?

**Comment by hawkowl** [comment]
`trial` is the best xUnit runner that Python has right now, which is really the only reason. I wouldn't be opposed to de-trialing the tests (and using stdlib/testtools/etc) to make them standard unittest, which you can run under whatever. I'd not love any pytest specific things unless there was something killer which made things way easier, though.

**Comment by ThiefMaster** [comment]
(Just my two cents even though I'm not working on this project and thus am not really affected by the choice of test runner)

Isn't the fact that stdlib `unittest` is littered with camelCase names reason enough to avoid using it? ;)

`pytest` is pretty much the standard nearly all modern Python projects use, it writing tests using pytest is much more pleasant than with `unittest`. Being able to just `assert foo == bar` without losing any metadata (such as the values of `foo` and `bar`) compared to `self.assertEqual(foo, bar)` is a huge plus IMO.

**Comment by altendky** [comment]
Without weighing in on how important it is, FYI we can't test on Windows with CPython 3.9 right now because you can't compile Twisted IOCP stuff and thus can't have trial.  Which of course is mostly an issue of trial not being it's own thing, or Twisted being behind, etc... but none the less.  And I guess also, Twisted is moving IOCP out so maybe this will be less of an issue in the future.

Enough rambling though.

**Comment by graingert** [comment]
from a quick glance it looks like it would be quite possible to switch out the test files to use stdlib `unittest.TestCase`.

That way you gain the flexibility to use the stdlib runner or trial or pytest.

I can probably find some time to do this if it's a desirable direction

**Comment by exarkun** [comment]
> That way you gain the flexibility to use the stdlib runner or trial or pytest.

Have you tried running the towncrier test suite with pytest?  It probably already works.  That's one of the strengths of xUnit - a standard set of abstractions and APIs makes different implementations more compatible than some of the other bespoke toolchains.

Anyhow, it doesn't seem like there's a consensus here that a switch to pytest makes sense.  Thanks for suggesting it.  It may be worth revisiting this in a few more years.  For now, I'll close this to reflect the fact that towncrier is sticking with trial.
