### ISSUE TITLE
Failure to run in GitHub Actions

### ISSUE THREAD

**Issue by sajith** [twisted/towncrier#175]
I'm trying to run  `python -m towncrier.check --pyproject towncrier.pyproject.toml` from GitHub Actions steps, and towncrier fails in this manner:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/hostedtoolcache/Python/2.7.17/x64/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/towncrier/check.py", line 98, in <module>
    _main()
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/towncrier/check.py", line 31, in _main
    return __main(compare_with, directory, pyproject)
  File "/home/runner/work/tahoe-lafs/tahoe-lafs/.tox/codechecks/lib/python2.7/site-packages/towncrier/check.py", line 44, in __main
    .decode(getattr(sys.stdout, "encoding", "utf8"))
TypeError: decode() argument 1 must be string, not None
```

That `sys.stdout.encoding` is set to `None` seems to be a GitHub Actions quirk, because this doesn't happen in TravisCI or CircleCI.

It happens on all three GA setups (Windows, macOS, Ubuntu) I tried.

More here: https://github.com/sajith/tahoe-lafs/runs/462170050#step:9:22.

**Comment by sajith** [comment]
This is simple to reproduce:

```
$ python -m towncrier.check --pyproject towncrier.pyproject.toml | less
```

**Comment by tjanez** [comment]
You can avoid this issue if you use Python 3.

Here are the relevant parts of a GitHub Actions workflow we use for [Oasis Core](https://github.com/oasislabs/oasis-core):

- [Setup up Python 3](https://github.com/oasislabs/oasis-core/blob/66d5a6292f9014ad5208fce2e34afd0ceff359af/.github/workflows/ci-lint.yml#L34-L37):

```yaml
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
```

- [Run the towncrier check command](https://github.com/oasislabs/oasis-core/blob/66d5a6292f9014ad5208fce2e34afd0ceff359af/.github/workflows/ci-lint.yml#L51-L60):

```yaml
      - name: Check for presence of a Change Log fragment (only pull requests)
        run: |
          # Fetch the pull request' base branch so towncrier will be able to
          # compare the current branch with the base branch.
          # Source: https://github.com/actions/checkout/#fetch-all-branches.
          git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
          towncrier check --compare-with origin/${BASE_BRANCH}
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        if: github.event_name == 'pull_request'
```

**Comment by sajith** [comment]
@tjanez Ah nice.  This is good to know.  Thank you!

Python 3 porting efforts of Tahoe-LAFS have a lot more progress to make, and I believe the idea is to retain compatibility with Python 2 for now.  Our test matrix has to have Python 2.

**Comment by tjanez** [comment]
> Python 3 porting efforts of Tahoe-LAFS have a lot more progress to make, and I believe the idea is to retain compatibility with Python 2 for now.

Aha, I understand.

> Our test matrix has to have Python 2.

Still, the towncrier check is not tied to Tahoe-LAFS being written in Python 2, you just need to make sure you use Python 3 for the towncrier check.

For example, if you use Tox, you could specify different `base_python` versions for different environments, e.g.:
```ini
[testenv]
basepython =
    py36,docs,linters,packaging,migrations: python3.6
    py37: python3.7
    py38: python3.8
```
(taken from: https://github.com/genialis/django-priority-batch/blob/0f91e47d0d4afa0e8bf62609cad929a6c4ffd6df/tox.ini#L19-L23).

**Comment by sajith** [comment]
Yes, there's a `tox.ini`.  There's also an `actions/setup-python@v1` step with `python-version: ${{ matrix.python-version }}` argument in my GitHub Actions setup.  I am not sure how the combination of Tox and GitHub Actions's Python setup will play together.

Let me toy with this.  Thank you for the idea!
