### ISSUE TITLE
Rendering issue with release candidate (19.9.0rc1)

### ISSUE THREAD

**Issue by acabarbaye** [twisted/towncrier#180]
When using the release candidate (19.9.0rc1), the title of the new entry in the Changelog is poorly formatted.

_This is using the same config as for 19.2.0._

There is duplication of the line:
```
"version" (2020-04-02)
====================
"package-name" "version" (2020-04-02)
=======================
```

**Comment by altendky** [comment]
For now I'll just document what I got instead.  Perhaps I can also figure something out about it.

```
pytest-trio 0.6.0+dev (2020-10-13)
----------------------------------
Pytest_Trio 0.6.0+dev (2020-10-13)
----------------------------------
```
