### ISSUE TITLE
Add support for subsections within each type

### ISSUE THREAD

**Issue by taldcroft** [twisted/towncrier#230]
The astropy core package (https://github.com/astropy/astropy) has substantial subpackages. The [changelog](https://github.com/astropy/astropy/blob/master/CHANGES.rst#41-unreleased) subdivides the sections (New Features, Bug Fixes, etc) by subpackage to help users identify changes relevant to their needs.

We are considering using towncrier but need to be able to specify the subpackage in the news fragment name and have this end up in the rendered CHANGES.rst output.

I'd be happy to work on a towncrier enhancement to add support for subsections, but would like some feedback in advance about whether this would be acceptable. I spent a little time looking at the code and it seems feasible, but it would be great to get some steering advice on the best way to make this possible.

One idea is to allow fragment file names like `<subsection>.<ticket>.<category>[.<counter>][.ext]`. Here `<subsection>` is the new bit and would need to match an entry in a new configuration `tool.towncrier.subtype` analogous to the current `tool.towncrier.type`.  If no match were found then it would just be ignored per current behavior.

**Comment by taldcroft** [comment]
Just a ping on this.  I'll take silence as an indication that the towncrier project would not be interested in astropy devs contributing such a feature.

**Comment by saimn** [comment]
I found by reading the code that there is an undocumented "section" feature (#61) which is almost that. Instead of adding "subsection" fragments it works with sub-directories, but this achieves the same goal.

**Comment by SmileyChris** [comment]
Yeah, I think the section feature works fine to achieve this. It's documented in the configuration reference now.
