### ISSUE TITLE
New release post 19.2.0 

### ISSUE THREAD

**Issue by hmaarrfk** [twisted/towncrier#269]
Recent updates have allowed for the use of a towncrier.toml file that doesn't conflict with pyproject.toml which triggers special pip behavior.

It would be nice to be able to use this.

A 20.XX release would be greatly appreciated!

Thanks!

**Comment by rohanpm** [comment]
I would also appreciate a new release for the sake of the `template = "towncrier:<bundled>"` feature added in 3d01a194a68f48d.

**Comment by hmaarrfk** [comment]
Sorry for bumping this request, but any news on this?

**Comment by altendky** [comment]
Aside from a release, I have asked a couple times in IRC about the review etc policies here.  I'll check on the maillist now too.

**Comment by saroad2** [comment]
Hey, I'm joining the request in this PR.
I would love to see a new release of *Towncrier* being released. Really want to start integrating it into my CI/CD  process.

If help is needed in review/implementing new features, let me know and I'll give a hand!

**Comment by altendky** [comment]
For awhile I had good momentum so I had planned to just finish out the rest of the stuff I was interested in before release, but the progress has slowed down.  I'll look back at doing a release soon without waiting for those other bits.

**Comment by altendky** [comment]
Welp, we're failing to get it done quickly but we are still doing stuff over in #313.

**Comment by hmaarrfk** [comment]
Thanks, i periodically check to see if i should delete my hacked version. Glad to see that you are simplifying the scope!

**Comment by altendky** [comment]
Well, kinda...  `:|`  Now we've fallen into the 'define and automate the release process before releasing instead of after' hole.  Lemme see where everything's at...

**Comment by hmaarrfk** [comment]
i guess i read too quickly ^_^

**Comment by hmaarrfk** [comment]
I'm going to say, that since you have CIs for testing, releasing a pure python package manually is not the end of the world. You could even distribute it as source....

**Comment by altendky** [comment]
Agreed.  It is a team effort here with multiple opinions.  But, I did make a work around for one of the hang ups and that got approved and merged.  I need to catch up https://github.com/twisted/towncrier/pull/315.  After that, the checklist in https://github.com/twisted/towncrier/issues/313 looks pretty free flowing.

Regardless, this is certainly frustrating for you and others.  I'm sorry for the hassle.  With a little luck this will be less painful in the future.  (and maybe next time I'll actually get the bits I wanted fixed and added included in the release `:]`)

**Comment by altendky** [comment]
Or maybe I already updated #315 three days ago and forgot amidst everything else...  Anyways, looking now.

**Comment by hmaarrfk** [comment]
i totally understand.

I just gave up on getting some of my automation "perfect" last week so I figured I would give a friendly nudge.

**Comment by altendky** [comment]
Nudges are certainly appropriate.  `:]`

**Comment by altendky** [comment]
21.3.0rc1 is out.  Maybe we can hit a 1 week RC this time.  :]

https://twistedmatrix.com/pipermail/twisted-python/2021-March/065566.html

**Comment by hmaarrfk** [comment]
just tried it out, seems to work for me :D

**Comment by altendky** [comment]
[19.9.0](https://pypi.org/project/towncrier/19.9.0/) and [21.3.0](https://pypi.org/project/towncrier/21.3.0/) are both available on PyPI.  \*phew\*  Thanks for all the patience here and my apologies for the hassle associated with it.

https://twistedmatrix.com/pipermail/twisted-python/2021-April/065580.html

**Comment by hmaarrfk** [comment]
woot!!!!

**Comment by hmaarrfk** [comment]
thanks for all the hard work
