### ISSUE TITLE
RTD is misconfigured redirecting to a dead link

### ISSUE THREAD

**Issue by webknjaz** [twisted/towncrier#273]
If you go to the root location at RTD https://towncrier.readthedocs.io/, it'll redirect to https://towncrier.readthedocs.io/en/latest/ with HTTP 404 there.

The problem is that this page is linked from https://github.com/twisted/towncrier/tree/actual-freaking-docs#documentation (that also shows up @ https://towncrier.readthedocs.io/en/actual-freaking-docs/#documentation).

The easiest hotfix is to just fix the link in `README.rst` in the `actual-freaking-docs` branch. But the better fix would be to go to RTD and configure the redirect properly.

**Comment by adiroiban** [comment]
I hope that this can be fixed by #367 once we have the docs in the main branch  and we got control over the Read the docs towncrier project

**Comment by hynek** [comment]
this has been fixed
