### ISSUE TITLE
Documentation in README is not accurate… Python 3.8 & 3.9 support?

### ISSUE THREAD

**Issue by ygworldr** [twisted/towncrier#281]
I tried to install the latest version `19.2.0` and followed the instructions in the README file. This is what I got:

```bash
√ (main|…2); bat pyproject.toml
───────┬────────────────────────────────────────────────────────────────────────
       │ File: pyproject.toml
───────┼────────────────────────────────────────────────────────────────────────
   1   │ [tool.towncrier]
   2   │ directory = "changes"
   3   │ filename = "NEWS.rst"
───────┴────────────────────────────────────────────────────────────────────────
√ (main|…2); lsd -a changes
 ./   .gitignore   ../
√ (main|…2); towncrier create 123.feature
Usage: towncrier [OPTIONS]
Try 'towncrier --help' for help.

Error: Got unexpected extra arguments (create 123.feature)
✗ 2 (main|…2); towncrier --help
Usage: towncrier [OPTIONS]

Options:
  --draft         Render the news fragments, don't write to files, don't check
                  versions.

  --dir TEXT
  --name TEXT
  --version TEXT  Render the news fragments using given version.
  --date TEXT
  --yes           Do not ask for confirmation to remove news fragments.
  --help          Show this message and exit.
```

This is a test project which is not a Python one. Still, I would have expected it to work.

There is a mention of `towncrier.ini` which I assume is a typo for `pyproject.toml`…

_Am I doing something wrong?_

**Comment by ygworldr** [comment]
I installed it via `python -m pip …` and I am using `pyenv` with Python 3.8.6. I tried a Fedora package install but I get the same error.

**Comment by ygworldr** [comment]
I looked at the `tox.ini` file: `{pypy3,py27,py35,py36,py37}` and there are no Python 3.8 or 3.9 so that might well be the problem…

**Comment by altendky** [comment]
The readme on the main GitHub page is for the latest development version that has not been released.  PyPI might be the easiest place to get a given readme for a released version.  if you use `--pre` when installing (and `--upgrade` if it is already installed) then you can get a prerelease that is at least more like the default readme on GitHub and will provide the subcommand interface.  That would be version 19.9.0rc1.

As for Python 3.8 and 3.9 support, it seems likely it would work but no, it isn't presently being tested on those versions.  Just this week I started to try to take a pass through the pull requests etc and adding testing for, and claiming compatibility with, 3.8 and 3.9 will hopefully come soon.

**Comment by ygworldr** [comment]
@altendky Thank you so much! I shall give that a try.

**Comment by ygworldr** [comment]
And it works like a charm! 

```bash
√ (main|✓); towncrier create towncrier.feature
Created news fragment at /home/yann/worldr/github/test-CI/changes/towncrier.feature
√ (main|…1); bat ./changes/towncrier.feature
───────┬────────────────────────────────────────────────────────────────────────
       │ File: ./changes/towncrier.feature
───────┼────────────────────────────────────────────────────────────────────────
   1   │ Add your info here
───────┴────────────────────────────────────────────────────────────────────────
√ (main|…1);
```

Please feel free to close this …
