### ISSUE TITLE
Support for multiple issues per news fragment

### ISSUE THREAD

**Issue by michael0liver** [twisted/towncrier#325]
There are cases where a PR closes multiple issues. Is it possible to do this using towncrier e.g. 
`123.128.bugfix`

**Comment by adiroiban** [comment]
I am doing that by creating multiple fragment files.

* /release-notes-fragments/123.bugfix  - in which I explain what bug 123 is and how it was fixed... or just that it was fixed
* /release-notes-fragments/128.bugfix  - in which I explain what bug 128 is and how it was fixed.

Would that work for you?

**Comment by michael0liver** [comment]
Yeah that is probably fine for my use case thanks.

P.S it would be great if you enabled the [Discussions](https://docs.github.com/en/discussions/quickstart) tab on this repository. It is probably a better place for these sorts of questions :)

**Comment by adiroiban** [comment]
Done -> https://github.com/twisted/towncrier/discussions 

Thanks :)
