### ISSUE TITLE
Avoid exception traceback with "towncrier check"

### ISSUE THREAD

**Issue by tomschr** [twisted/towncrier#336]
# Situation

When calling `towncrier check` in a directory without any Towncrier config files, you get this exception:

```
$ mkdir /tmp/towncrier-test; cd /tmp/towncrier-test
$ python3 -m venv .env
$ source .env/bin/activate
$ .env/bin/pip install towncrier
$ pip show towncrier
Name: towncrier
Version: 21.3.0
[...]
Location: /tmp/towncrier-test/.env/lib/python3.6/site-packages
$ .env/bin/towncrier check
Traceback (most recent call last):
  File ".env/bin/towncrier", line 8, in <module>
    sys.exit(cli())
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/towncrier/check.py", line 27, in _main
    return __main(compare_with, directory, config)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/towncrier/check.py", line 32, in __main
    base_directory, config = load_config_from_options(directory, config)
  File "/tmp/towncrier-test/.env/lib64/python3.6/site-packages/towncrier/_settings.py", line 49, in load_config_from_options
    "No configuration file found.\nLooked in: %s" % (base_directory,)
towncrier._settings.ConfigError: No configuration file found.
Looked in: /tmp/towncrier-test
```

# Proposed solution

The traceback shouldn't be displayed. Don't frighten our users. :wink: IMHO it's completely enough if we catch it and output only the error message:

```
$ .env/bin/towncrier check
towncrier._settings.ConfigError: No configuration file found.
Looked in: /tmp/towncrier-test
$ echo $?
1
```

# Possible dependencies

Maybe related to #306

**Comment by adiroiban** [comment]
Thanks the report. Agree.
I also think that this is related to #306 

As commented in 306, either use click exception, or add code to handle `towncrier._settings.ConfigError`

For this particular case maybe  raise click.FileError ? https://click.palletsprojects.com/en/7.x/exceptions/#which-exceptions-exist

**Comment by chrysle** [comment]
Can I work on this?

**Comment by adiroiban** [comment]
Hi @chrysle 

You are welcome to give this a try.

You can create a PR and write the minimal test for it to check that the full traceback is no longer visible.

**Comment by chrysle** [comment]
> For this particular case maybe raise click.FileError ? https://click.palletsprojects.com/en/7.x/exceptions/#which-exceptions-exist

I don't think this will be much less frightening (?): 

```
Error: Could not open file '/home/user': unknown error
```

**Comment by chrysle** [comment]
The problem is that if the `config_path` is `None`, only `base_directory` can be passed to the exception. 

It would maybe be better just to print: 

```
No configuration file found.\nLooked in: {base_directory}
```

**Comment by adiroiban** [comment]
The last suggestion is ok.
I think that the main issue here is that the ConfigError is  not handled/caught so we have the traceback. 
Thanks

**Comment by chrysle** [comment]
@adiroiban Could you make a suggestion for a test?

My problem is that there is no suitable assert in the [trial assertions](https://docs.twistedmatrix.com/en/stable/api/twisted.trial._synctest._Assertions.html) , like `assertNotRaises`.
