### ISSUE TITLE
Rework CONTRIBUTING file

### ISSUE THREAD

**Issue by tomschr** [twisted/towncrier#342]
# Situation

As a first time contributor, I've read the `CONTRIBUTING.rst` before. Although I went through it, I got the impression it _doesn't talk to me_. :wink: It seems to be written for people who _release_ towncrier or have admin rights. This gave me the feeling I was not the target group.

# Proposed solution

As this is a relevant and essential file of this project, we should address and attract potential contributors and not confuse them. I would suggest:

* Distinguish between content that is needed for project admins and contributors.
* Clearly address your target group (first time/occasional developer vs. project admin). 
* Use the `CONTRIBUTING.rst` file *only* for contributors and move the existing content to another file.
* Provide a concise step-by-step introduction which could also be used as a checklist.
* Give some recommendations where necessary.

Here is an example what I did in another project: https://python-semver.readthedocs.io/en/latest/development.html It's probably not perfect, but it serves as a source for inspiration. :wink:

**Comment by altendky** [comment]
Agreed, having a proper introduction for incoming contributors would be good.
