### ISSUE TITLE
title repeated twice when title_format is set

### ISSUE THREAD

**Issue by BayerSe** [twisted/towncrier#346]
First of all, I would like to thank everyone working on this project. It eases our changelog generation a lot!

After upgrading our dependencies I have spotted some changed behavior. To illustrate this, I have created a fresh Python 3.9.4 project with just minimal code and `towncrier==21.3.0`.

When I configure `towncrier` like this:

```
[tool.towncrier]
title_format = "{version} ({project_date})"
```

Then the output of `towncrier build --version=0.1 --draft` is

```
0.1 (2021-04-27)
=================

Features
--------

- This is only a test. (#1)
```

as expected. However, the content of `NEWS.rst` after `towncrier build --version=0.1` is

```
0.1 (2021-04-27)0.1 (2021-04-27)
================

Features
--------

- This is only a test. (#1)
```

where we can see that the title is duplicated.

**Comment by hynek** [comment]
I suspect this is related to #340 too

**Comment by saimn** [comment]
We have the same issue (https://github.com/astropy/astropy/pull/12083). The problem seems to be that `top_line` is both written by the code (https://github.com/twisted/towncrier/blob/5dce0fad4973b859a68896b51ac87ec46c0f0312/src/towncrier/_writer.py#L41-L42) and present in the default template. I guess it just be written only with the template.

**Comment by kasium** [comment]
@adiroiban can you please release a new version with the fix

**Comment by adiroiban** [comment]
PR here . https://github.com/twisted/towncrier/pull/360 
Please check that the release candidate is ok https://pypi.org/project/towncrier/21.9.0rc1/

thanks!

**Comment by decaz** [comment]
@adiroiban is stable version can be released now, please?

CC @graingert @altendky @hukkin
