### ISSUE TITLE
Add multiple changelog segments in one PR

### ISSUE THREAD

**Issue by bsipocz** [twisted/towncrier#355]
I would have the feature requests for being able to add multiple changelog segments in one PR, segments that end up in the same section of the changelog.

I think it's beneficial in many cases to have multiple entries rather than one long paragraph for new feature additions, but for maintenance supporting this would be crucial. E.g. in a project, I'm dropping support for multiple dependency versions. All of those need their clean, short changelog entry and currently, I am bound to open separate PRs for this to be able to handle the changelog, even though logically and logistically it would be much nicer to do it in one go.

**Comment by Cadair** [comment]
Isn't this the feature that was added in https://github.com/twisted/towncrier/pull/119 ?

**Comment by bsipocz** [comment]
Yes, I suppose that's exactly what I was looking for.

**Comment by pawelad** [comment]
Is this feature still supported? I'm getting an error when trying to use it:

```console
$ towncrier create 2585.changed.1.md
Usage: towncrier create [OPTIONS] FILENAME
Try 'towncrier create --help' for help.

Error: Invalid value: Expected filename '2585.changed.1.md' to be of format '{name}.{type}', where '{name}' is an arbitrary slug and '{type}' is one of: feature, bugfix, doc, removal, misc
```

EDIT: I decided to create a new issue instead of hijacking this one - #474
