### ISSUE TITLE
"TypeError: string indices must be integers" when trying to use custom newsfragments types.

### ISSUE THREAD

**Issue by danieljmv01** [twisted/towncrier#361]
# Situation
I was trying to use custom newsfragments types since there is a mention about it in the [docs](https://towncrier.readthedocs.io/en/actual-freaking-docs/quickstart.html#creating-news-fragments) and I was curious about it.

I included pyproject.toml: 
```
[tool.towncrier.type.feat]
directory="feat"
name="Feature"
showcontent=true

[tool.towncrier.type.fix]
directory="fix"
name="BugFix"
showcontent=true

[tool.towncrier.type.misc]
directory="misc"
name="Misc"
showcontent=false

[tool.towncrier.type.docs]
directory="docs"
name="Docs"
showcontent=true

[tool.towncrier.type.foo]
directory="Foo"
name="Misc"
showcontent=false

```

And it (`towncrier check`) resulted in the exception "TypeError: string indices must be integers".

https://github.com/twisted/towncrier/blob/0e6a4793bb786053c491fde52ea2667c73807f75/src/towncrier/_settings.py#L104-L105

As is, the loop is iterating over the keys of the dictionary, `x` is a string.

# Proposed solutions

It think that the loop was expected to iterate over the values instead, something like:
```python
 for x in config["type"].values(): 
     types[x["directory"]] = {"name": x["name"], "showcontent": x["showcontent"]} 
```

 It would be interesting too to make  "directory"  optional in the config. Something like:

```python
newtypes_config = config["type]
for newtype_name, newtype_params in newtypes_config.items():
     type_directory = newtype_params.get("directory", newtype_name)
     types[directory] = {"name": newtype_params["name"],  "showcontent": newtype_params["showcontent"]} 
```

Thank you very much!

**Comment by danieljmv01** [comment]
In the [configuration docs](https://towncrier.readthedocs.io/en/actual-freaking-docs/configuration.html) there is no reference to custom types, but there is an example in Readme.rst, and it works fine. 
So this probably the error is because I configured it in a way it was not expected. Sorry.

**Comment by MaxWinterstein** [comment]
@danieljmv01 what is the end of the story? 

Adding custom types via the deprecated way
```toml
[[tool.towncrier.type]]
directory = "dev"
name = "Development"
showcontent = true
```

Works for me as desired, but not the _new_ way, neither `[tool.towncrier.dev]`, nor `[tool.towncrier.fragment.dev]`. Using `[tool.towncrier.type.dev]` throws mentioned exception from above.
