### ISSUE TITLE
Update PYPI Project links .

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#366]
Some links our outdated or dead pages :)

https://pypi.org/project/towncrier/

A refresh would help.

**Comment by bignose-debian** [comment]
> Some links our outdated or dead pages :)
> https://pypi.org/project/towncrier/

I think maybe you are referring to the “Project links” section on that page?

If so, I don't know which ones are outdated. Can you enumerate the ones you believe need to be updated, and what they should be now?

 I followed each of them and they all resolve except one: the “Maillist” redirects and then ends up at a 404 Not Found response. Maybe there is no mailing list for Town Crier, so this link can be removed?

**Comment by adiroiban** [comment]
These 2 links

https://github.com/twisted/towncrier/blob/97471742ca6b7669cdfb89b8b4cc8cdc493b2157/setup.py#L17-L18

Mail is now at https://mail.python.org/mailman3/lists/twisted.python.org/
IRC is Libera  or Matrix/Gitter https://gitter.im/twisted/twisted

--------

And we now have documentation https://towncrier.readthedocs.io/en/latest/

**Comment by bignose-debian** [comment]
I have made these changes (with a corresponding news fragment) in the branch [wip/issue/366/pypi-project-urls](https://salsa.debian.org/bignose/towncrier/-/commits/wip/issue/366/pypi-project-urls) at my [personal fork repo](https://salsa.debian.org/bignose/towncrier/).

The branch merges cleanly to current ‘master’ branch.

**Comment by adiroiban** [comment]
Thanks, @bignose-debian for the changes. I have created a PR and pushed the changes.

I have not used your commits and it's more complicated to sync the repos.

Hope all is ok.

**Comment by bignose-debian** [comment]
> Thanks, @bignose-debian for the changes. I have created a PR and pushed the changes.

Glad to have helped.

> I have not used your commits and it's more complicated to sync the repos.

Git is a distributed VCS, and merging between multiple repositories is built in. GitHub fails to collaborate well between repositories from other providers, which is a shortcoming of GitHub.

But normal Git operations allow using any remote repository normally. So I hope you can re-visit this to allow for more distributed development letting developers choose where to host their repositories.

With that said, thank you for improving the software, and I'm glad these improvements made it into the project.

**Comment by adiroiban** [comment]
I know that you can have multiple remotes for git ... but it takes time.

I am doing this in my free time, trying to help with towncrier.... even though I am using a 5 years old towncrier version, that works for me.

If anyone want to take over towncrier maintenance, I am more than happy to see other people merging PRs and patches :)

-------

But for now, the contribution guide asks for contributors to create a PR in GitHub.
 
I am not a fan of GitHub or MS, but at this point, GitHub is convenient and easy to collaborate with, even when you are doing this as your 3rd or 4th job with little time.

freedom isn't free  and at this point, I don't have time for this.
