### ISSUE TITLE
 Move the documentation into the main repo and branch.

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#367]
The current doumentation is generated via https://readthedocs.org/projects/towncrier/

and the code is from a separate branch https://github.com/twisted/towncrier/tree/actual-freaking-docs

I think that in order to make things less confusing and have a lean dev process, we should move the docs into the main branch.

I don't have access right now to towncrier RTD project and @hawkowl  is the only admin.

I hope Amber can see this notification and can add myself and maybe Glyph to the list of maintainers.

**Comment by danieljmv01** [comment]
@adiroiban  I have rebased the actual-freaking-docs  on `master`, and added a commit to include how to configure custom fragments types at the current state of the code.

I can squash the commits, or drop the one that I added if you decide so.
