### ISSUE TITLE
Keep new lines in the release notes

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#37]
So... the releases managers are on Linux and Unix... all is fine... but when you have a release manager using Windows, when she/he runs the tool to generate the release notes the file is updated with windows new lines.

.... not  sure how to do... maybe have an option where you can specify what new lines to use

**Comment by adiroiban** [comment]
I am going to close this. I found this issue a long time ago and I think that since then this might be fix.
Anyway, we can reopen this if this is a real issue.

**Comment by hynek** [comment]
you didn't close it :)
