### ISSUE TITLE
tox  does not have a `skip_missing_envs` setting.

### ISSUE THREAD

**Issue by danieljmv01** [twisted/towncrier#371]
https://github.com/twisted/towncrier/blob/27cd970aaa76167ecdc054bdb26cf6763ffa0ed8/tox.ini#L1-L4

The setting `skip_missing_envs` included in the `[tox]` section of the `tox.ini` is not a tox setting, at least in the most recent versions of tox.
It is likely that it was confused with `[skip_missing_interpreters](https://tox.wiki/en/latest/config.html#conf-skip_missing_interpreters)`.

**Comment by adiroiban** [comment]
Most probably.

This was introduced here https://github.com/twisted/towncrier/commit/4068ee4a7e9aaca2f2fafb44665df5e4a1ec7aab

there is also #319 which tries to prepare for tox v4.

I am not a big tox fan. I keep it's usage to the minimum.

But I am happy to review and merge any improvement on tox.

**Comment by SmileyChris** [comment]
We're using nox, not tox now, so this is a non-issue.
