### ISSUE TITLE
Save the planet

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#379]
I think that is safe to run pypy test only on Linux.

They take ridiculous amount of time on Win ... compared with less than 2 minutes on Linux.

![image](https://user-images.githubusercontent.com/204609/162431503-a3d91c5d-6b85-49c7-bf91-c2ba9c408893.png)

And I think that for macOS and Windows, we can live with just running cPython 3.10 tests.

All this to reduce the resource used to run our CI matrix.

**Comment by hynek** [comment]
I think it's fair enough to have some kind of integration on weird platforms, but macOS is not weird enough and it should be just one each. IOW Win-{CPy-3.9,PyPy-3.8} and the rest just Linux.

**Comment by hynek** [comment]
Oh and re: PyPy: it's brutally slow under coverage, so I've stopped in my projects. I wouldn't expect towncrier to have any pypy-specific code, so that could be optimized.
