### ISSUE TITLE
incremental version

### ISSUE THREAD

**Issue by papoteur-mga** [twisted/towncrier#385]
Hello,
I see that incremental module is required to be 17.5.0
https://github.com/twisted/towncrier/blob/ab2b5ac824032c1a0f04409c8e26efebc4f5f59d/pyproject.toml#L66
Does that mean that the application will not work with another module release like 21.3.0, the minimum release required by twisted?
I ask that because in my distribution, I have to update python-twisted to 22.4 for security reason.

**Comment by adiroiban** [comment]
I think it will work with other versions.
I would be happy to see a PR removing the requirement for "incremental".

I don't think that incremental is such a big deal for the build system and without an "incremental" requirements it should be much easier to install and update towncrier.

btw. I am using a fork of towncrier in which I have removed the "incremantal" usage.

**Comment by papoteur-mga** [comment]
Indeed, I saw #308
Thanks for you answer.

**Comment by adiroiban** [comment]
I will close this and I will try to work on #308
