### ISSUE TITLE
`title_format` doesn't work in 21.9.0

### ISSUE THREAD

**Issue by Zlopez** [twisted/towncrier#386]
I have `title_format = "{version} ({project_date})"` in my pyproject.toml `[towncrier]` section and in towncrier 21.9.0 this seems to be ignored. The title is missing in both `--draft` and the generated file.

This worked in the past, but with the latest version it doesn't work anymore.

The whole configuration file can be found [here](https://github.com/fedora-infra/the-new-hotness/blob/master/pyproject.toml).

**Comment by adiroiban** [comment]
I see that this functionality was touched as part of #346

**Comment by adiroiban** [comment]
Ok.

I think that the quick fix is to update your template and add at the start

```
{% if render_title %}
{% if versiondata.name %}
{{ versiondata.name }} {{ versiondata.version }} ({{ versiondata.date }})
{{ top_underline * ((versiondata.name + versiondata.version + versiondata.date)|length + 4)}}
{% else %}
{{ versiondata.version }} ({{ versiondata.date }})
{{ top_underline * ((versiondata.version + versiondata.date)|length + 3)}}
{% endif %}
{% endif %}
{% for section, _ in sections.items() %}
{% set underline = underlines[0] %}{% if section %}{{section}}
{{ underline * section|length }}{% set underline = underlines[1] %}

{% endif %}
```

to match the default template.

----------

The current towncrier config is a bit of mess.

I think most configuration values are only valid when using the default template.

**Comment by Zlopez** [comment]
I tried to add the lines to the `_template.rst` and still nothing.

Output of `towncrier --draft`
```
Loading template...
Finding news fragments...
Rendering news fragments...
Draft only -- nothing has been written.
What is seen below is what would be written.



Bug Fixes
---------

* Failure when converting the redis value to integer
  (`PR#475 <https://github.com/fedora-infra/the-new-hotness/pull/475>`_)

```

The correct output should be 

```
Loading template...
Finding news fragments...
Rendering news fragments...
Draft only -- nothing has been written.
What is seen below is what would be written.


1.2.0 (2022-06-02)
==================

Bug Fixes
---------

* Failure when converting the redis value to integer
  (`PR#475 <https://github.com/fedora-infra/the-new-hotness/pull/475>`_)

```

**Comment by Zlopez** [comment]
Hm, it seems that the issue must be somewhere in my configuration than. I will try to look at it more closely later.

**Comment by Zlopez** [comment]
The behavior of the towncrier is inconsistent in this case. I used the default template again and now it worked. So I tried to add the macro I have in my own and it stopped working, so I removed the macro again and now the title doesn't work anymore, even if I'm in the same state that worked before.

Does towncrier has any cache or something, that could cause this?

**Comment by Zlopez** [comment]
After some playing I figured out that the issue is actually in https://github.com/twisted/towncrier/blob/master/src/towncrier/_builder.py#L284 the `top_line` is provided, but the `render` is ignoring it sometimes.

I have Jinja2 3.1.2 in my virtual env.

**Comment by Zlopez** [comment]
When I copied over this part of default template from the 21.9.0
```
{% if top_line %}
{{ top_line }}
{{ top_underline * ((top_line)|length)}}
{% elif versiondata.name %}
{{ versiondata.name }} {{ versiondata.version }} ({{ versiondata.date }})
{{ top_underline * ((versiondata.name + versiondata.version + versiondata.date)|length + 4)}}
{% else %}
{{ versiondata.version }} ({{ versiondata.date }})
{{ top_underline * ((versiondata.version + versiondata.date)|length + 3)}}
{% endif %}
```
to my template it started working like a charm :-)

It looks that the only thing I was missing was the `top_line` in my template. I assume this will no longer work with next release, because the `top_line` is no longer in the current master.

**Comment by adiroiban** [comment]
Yes. The `top_line` is no longer part of the public API.

There is missing documentation for towncrier template design API and no commitment from towncrier devs to keep backward compatibility.

https://github.com/twisted/towncrier/blob/21c11748e9c21c270b221af28d07baf93fdb1980/src/towncrier/_builder.py#L284-L292

------

The main issue is that towncrier lacks some dev love ... so there is no much we can do now.

**Comment by adiroiban** [comment]
I think that this can be closed.

Somehow a fix would be to write documentation for what is public API available  inside  the templates.

**Comment by timwsuqld** [comment]
We are having this issue too. The fix that @Zlopez had of adding things to the template, will that continue working, or is there another workaround we'll need in the next release?
