### ISSUE TITLE
configuration.rst too old, to be updated immedately

### ISSUE THREAD

**Issue by mikesongming** [twisted/towncrier#389]
according to git blame history, some part was written 5 years ago, totally unconsistent with current setting:

> ### Top level keys
> package -- The package name of your project. (Python projects only)
> package_dir -- The folder your package lives. ./ by default, some projects might need to use src. (Python projects only)
> newsfile -- The filename of your news file. NEWS.rst by default.
> fragment_directory -- If you are not storing your newsfragments in your Python package, or aren't using Python, this is the path to where your newsfragments will be put.
> template -- Path to an alternate template for generating the newsfile, if you have one.
> start_line -- The magic string that towncrier looks for when considering where the release notes should start. .. towncrier > release notes start by default.
> title_format -- A format string for the title of your project. {name} {version} ({project_date}) by default.
> issue_format -- A format string for rendering the issue/ticket number in newsfiles. #{issue} by default.
> underlines -- The characters used for underlining headers. ["=", "-", "~"] by default.

**Comment by adiroiban** [comment]
Thanks for raising this. I agree that this is an issue and would be awesome to have the documentation updated.

**Comment by adiroiban** [comment]
We have this info https://towncrier.readthedocs.io/en/stable/#further-options

and then also this https://towncrier.readthedocs.io/en/stable/configuration.html#top-level-keys

It looks like duplicate info.

I think the "further-options" should be moved/merged into the `configuration - top level key`

**Comment by SmileyChris** [comment]
The configuration docs were updated some time last year, fixing this issue.
