### ISSUE TITLE
Add strict packaging validation as part of CI checks

### ISSUE THREAD

**Issue by adiroiban** [twisted/towncrier#457]
> and here [twisted/towncrier/actions/runs/3741354542](https://github.com/twisted/towncrier/actions/runs/3741354542)

If you look at https://github.com/twisted/towncrier/actions/runs/3741354542/jobs/6350891579#step:9:19 closer, you'll see warnings being emitted:
```console
Checking dist/towncrier-22.12.0rc1-py3-none-any.whl: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/towncrier-22.12.0rc1.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
```

P.S. In general, it's a good idea to run `twine check --strict` at early stages. My pypi-publish action also has a strict mode, but it's not pleasant to see hard failures at the very last moment before the release.

_Originally posted by @webknjaz in https://github.com/twisted/towncrier/issues/456#issuecomment-1359524318_

**Comment by hynek** [comment]
*cough* https://github.com/hynek/build-and-inspect-python-package 😇

**Comment by adiroiban** [comment]
Happy to use any existing tool.
I think this action is a good start.
