### ISSUE TITLE
Getting `CRITICAL 'Config' object is not subscriptable` error in 22.12.0

### ISSUE THREAD

**Issue by namurphy** [twisted/towncrier#461]
We just ran into a new error with the changelog part of our documentation build after the recent release of towncrier `22.12.0`, which does not occur with `22.8.0`.  I'm trying to fix it in https://github.com/PlasmaPy/PlasmaPy/pull/1850.  Here's a link to the most recent [build failure](https://github.com/PlasmaPy/PlasmaPy/actions/runs/3754237824/jobs/6378285534).

We have a file, [`docs/whatsnew/dev.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/whatsnew/dev.rst), which on our `main` branch is:
```rst
:orphan:

.. changelog::
   :towncrier: ../../
```
It's referred to within a toctree in our `docs/whatsnew/index.html`.

After the `22.12.0` release, we starting getting this error:
```
/home/runner/work/PlasmaPy/PlasmaPy/docs/whatsnew/dev.rst:3: CRITICAL: 'Config' object is not subscriptable
```
I'm not sure if the `Config` object refers to [`Config` from `load.py` in towncrier](https://github.com/twisted/towncrier/blob/ca12ad563d2c65338a739eea9a3a9d6938ff35c2/src/towncrier/_settings/load.py#L33) or [`sphinx.sphinx.config.Config`](https://github.com/sphinx-doc/sphinx/blob/984416247370a87ad947d89f334a8ce2d8ea6558/sphinx/config.py#L66).  I'm also not sure if this is related to something peculiar to our setup, or something more general.

(We also got a new missing title error for `dev.rst`, which we fixed by adding a title.)

Thank you!

**Comment by namurphy** [comment]
Here's the logging I got from building the docs locally with the verbosity turned up to ~~eleven~~ three (i.e. `sphinx-build -v -v -v`):
```
reading sources... [ 99%] whatsnew/dev
[app] emitting event: 'env-purge-doc'(<sphinx.environment.BuildEnvironment object at 0x7fd61ef4c9a0>, 'whatsnew/dev')
[app] emitting event: 'source-read'('whatsnew/dev', ['Unreleased changes\n==================\n\n.. changelog::\n   :towncrier: ../../\n
Loading template...
[app] emitting event: 'doctree-read'(<document: <section "unreleased changes"...>>,)
/home/namurphy/Projects/PlasmaPy/docs/whatsnew/dev.rst:4: (SEVERE/4) ‘Config’ object is not subscriptable

.. changelog::
   :towncrier: ../../
 [filtered system message]
reading sources... [100%] whatsnew/index
[app] emitting event: 'env-purge-doc'(<sphinx.environment.BuildEnvironment object at 0x7fd61ef4c9a0>, 'whatsnew/index')
[app] emitting event: 'source-read'('whatsnew/index', ['.. _change-log:\n\n#########\nChangelog\n#########\n\nThis document lists the c
[app] emitting event: 'doctree-read'(<document: <target...><section "changelog; change-log"...>>,)

[app] emitting event: 'env-updated'(<sphinx.environment.BuildEnvironment object at 0x7fd61ef4c9a0>,)
[app] adding js_file: 'https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^1.0.1/dist/embed-amd.js', {'priority': 500}
/home/namurphy/Projects/PlasmaPy/docs/whatsnew/dev.rst:4: CRITICAL: 'Config' object is not subscriptable
looking for now-outdated files... [app] emitting event: 'env-get-updated'(<sphinx.environment.BuildEnvironment object at 0x7fd61ef4c9a0>,)
none found
pickling environment... done
checking consistency... [app] emitting event: 'env-check-consistency'(<sphinx.environment.BuildEnvironment object at 0x7fd61ef4c9a0>,)
```

**Comment by hynek** [comment]
Yeah looks like sphinxcontrib-towncrier is accessing the `Config` object.

**Comment by adiroiban** [comment]
Thanks @namurphy for the report and @hynek  for following up with the "upstream" report.

I think that this can be closed.

The towncrier settings are still a private API. The extension is using the private API, so we should expect to see similar issues from time to time.

It would be nice to have a stable API... but it takes time, and we don't have much time for towncrier.

I am happy to access a PR in which a public settings API is defined.

----------

At this point, I think that the public API should be done at the .toml level.
And I think we are already have the TOML config schema documented and I remember that we did some changes that took backward compatibility into consideration

**Comment by webknjaz** [comment]
> Yeah looks like sphinxcontrib-towncrier is accessing the `Config` object.

Yes, but the OP's project does not use my extension — it uses `sphinx-changelog==1.2.0`.

**Comment by hynek** [comment]
Hyruuuuuuum!!!

**Comment by webknjaz** [comment]
I know, but I have a good reason for abusing the private API — reimplementing the config interpretation on the extension side would have as much fragility, if not more, unfortunately. Honestly, I don't understand why CLI apps often don't have a public API layer that would be a proxy between CLI and private API.
FWIW, this is one of the reasons I'm still marking all the extension versions as alpha-releases to signal that it needs improvements. Maybe I need to consider adding an upper bound to the dependency and bump it each time a new release of Towncrier happens to have the ability to vet it…

**Comment by pllim** [comment]
This is the sphinx-changelog usage. What needs changing over here? Thanks!

https://github.com/OpenAstronomy/sphinx-changelog/blob/main/sphinx_changelog/towncrier.py

**Comment by hynek** [comment]
> This is the sphinx-changelog usage. What needs changing over here? Thanks!
> 
> 
> 
> https://github.com/OpenAstronomy/sphinx-changelog/blob/main/sphinx_changelog/towncrier.py

You have to replace all the `config["foo"]` accesses by `config.foo`. I don't _think_ any names changed, but can't guarantee it from my phone.

**Comment by webknjaz** [comment]
Or use `dataclasses.asdict()` like we did in sphinxcontrib-towncrier.

**Comment by namurphy** [comment]
Thank you to everyone for the responses!  

I agree that this is ready to be closed from the point of view of towncrier, though waiting a month would make it easier to find for anyone else who runs into this issue, and perhaps prevent some duplicate issues. 

I'm wondering if it would make sense for the packages built upon towncrier to add a cron test against the `trunk` branch of towncrier.  Doing that would make it easier to find any issues like this before they make it to production.  

Thank you again!

**Comment by webknjaz** [comment]
> I'm wondering if it would make sense for the packages built upon towncrier to add a cron test against the `trunk` branch of towncrier.

Yes, it does make sense as a non-voting job, or even only running on cron. Using `pip install https://github.com/twisted/towncrier/archive/refs/heads/trunk.zip` would be helpful for this.

**Comment by hynek** [comment]
I think this can be closed.
