### ISSUE TITLE
Switch to hatchling?

### ISSUE THREAD

**Issue by hynek** [twisted/towncrier#471]
I'm currently three layers[^lay] deep yak-shaving, but given that:

1. [pip / setuptools interaction is broken on 3.12](https://github.com/pypa/setuptools/issues/3661)
2. [Twisted has switched to hatchling](https://github.com/twisted/twisted/blob/trunk/pyproject.toml)

Would ya'll be interested to move towncrier to a static config too? Given the simplicity of our setup.py, it should be a simple switcheroo.

[^lay]: I wanted to simplify our CI according to https://hynek.me/articles/why-i-like-nox/, but we have no pre-release so I wanted to add a pre-release, but just adding 3.12 to the noxfile explodes as explained in 1.

**Comment by altendky** [comment]
I've never worked with hatchling, but as you say, this is a pretty simple project and it shouldn't be a big deal.  No concerns from me.

What exactly is the need to switch to make pre-releases?

**Comment by hynek** [comment]
It doesn't, but I want to add the block that unpacks pre-release identifiers (`~3.12...`) to a normal version (`3.12`) and it would be pointless if there were no pre-release identifier in the matrix. :)

**Comment by adiroiban** [comment]
Should be ok to switch. Thanks for looking into this.

**Comment by hynek** [comment]
ref #467 as a reminder
