### ISSUE TITLE
``towncrier create -c`` doesn't retain RST syntax 

### ISSUE THREAD

**Issue by HealthyPear** [twisted/towncrier#476]
I noticed that if I do e.g.

`towncrier create -c "Deprecated module ``bla``" 3.deprecated.rst`

the file content loses the RST syntax to display code, 

``Deprecated module bla``

as opposed with writing the file your self (or using the ``--edit`` flag) which instead retains it.

**Comment by hynek** [comment]
That's a shell escaping problem. Try using single quotes instead of double quotes.

**Comment by HealthyPear** [comment]
Thank you that worked.

I think the documentation should be updated to explain this.

**Comment by adiroiban** [comment]
I am not sure if this is `towncrier` issue.

This is generic Unix shell behavior.

You will get the same issue if you would try to use the `echo` command, as an example.

The towncrier docs should be focesed on towncrier, not a bash tutorial :)

But, if a PR is summited, I would not reject it.

So @HealthyPear if you think this is a big issue, please suggestion where and how to improve the current documentation 

I am closing this for now. We can reopen it if needed.

Regards

**Comment by HealthyPear** [comment]
> I am not sure if this is `towncrier` issue.
> 
> This is generic Unix shell behavior.
> 
> You will get the same issue if you would try to use the `echo` command, as an example.
> 
> The towncrier docs should be focesed on towncrier, not a bash tutorial :)
> 

True, but the fact that I had to open the issue here and not interface with bash devs means that the naïve user expectation is for this to work (also because in the docs you make use of examples which uses both types of quotes).
Since it's not supposed to work for the reason you explained, I would say a simple note box with such an explanation might suffice.

> But, if a PR is summited, I would not reject it.
> 
> So @HealthyPear if you think this is a big issue, please suggestion where and how to improve the current documentation
> 

I can open the PR, maybe not today, but it's really an easy "fix".

> I am closing this for now. We can reopen it if needed.
> 
> Regards
