### ISSUE TITLE
Avoid `bytes` type in test process output

### ISSUE THREAD

**Issue by bignose-debian** [twisted/towncrier#479]
A few of the unit test cases make direct comparison to objects of type `bytes`. This can fail when the terminal stream is not in the assumed hard-coded encoding.

Instead, the test cases should avoid direct use of `bytes` where text is intended.

Either by re-writing what the test case is comparing; or by decoding the process output using the stream's actual encoding.

**Comment by bignose-debian** [comment]
The branch [wip/issue/479/avoid-bytes-for-command-output](https://salsa.debian.org/bignose/towncrier/-/tree/wip/issue/479/avoid-bytes-for-command-output) (in my [personal fork repository](https://salsa.debian.org/bignose/towncrier/)) contains a series of commits to address this issue.

The branch currently merges cleanly to the 'trunk' branch.

**Comment by hynek** [comment]
I believe all changes have also been part of #530 and are therefore applied.
