### ISSUE TITLE
Test CLI using click.testing.CliRunner

### ISSUE THREAD

**Issue by bignose-debian** [twisted/towncrier#481]
The unit test cases for CLI behaviour are using a 'click.testing.CliRunner', which correctly separates the Click behaviour to be tested, versus the particular way an executable program was or was not installed.

There are some remaining test cases that directly invoke a sub-process expecting the 'towncrier' command to be available. These should all use a 'click.testing.CliRunner' to avoid that coupling.

**Comment by bignose-debian** [comment]
The branch [wip/issue/481/use-clirunner-consistently](https://salsa.debian.org/bignose/towncrier/-/commits/wip/issue/481/use-clirunner-consistently) (in my [personal fork repository](https://salsa.debian.org/bignose/towncrier/)) contains a series of commits to address this issue.

The branch currently merges cleanly to the 'trunk' branch.

**Comment by SmileyChris** [comment]
> The branch [wip/issue/481/use-clirunner-consistently]
> The branch currently merges cleanly to the 'trunk' branch.

Sounds like you should open up a pull request against your branch then :)

**Comment by bignose-debian** [comment]
> Sounds like you should open up a pull request against your branch then :)

Unless I'm mistaken, GitHub has never been able to use its proprietary "pull request" system on remote repositories.

So it's up to the GitHub users to [get changes from remote repositories](https://docs.github.com/en/get-started/using-git/getting-changes-from-a-remote-repository), using the normal Git distributed features.

**Comment by adiroiban** [comment]
Thanks Ben for creating this issue on GitHub.

I am sure that when someone will have time for towncrier maintance, they will pick up your changes and try to merge them.

I tried to do a quick review on Salsa, but it looks like trunk branch is not available

https://salsa.debian.org/bignose/towncrier/-/compare/trunk...wip%2Fissue%2F481%2Fuse-clirunner-consistently?from_project_id=35328&straight=false

------------

I will not comment on GitHub vs GitLab.
I am not a supporter of MS nor GitHub.
But for now, GitHub it's what is used by Towncrier devs and it provides tools for open colaboration.

We don't have the resources to run our private GitLab :( 

I tried to login into Debian Gitlab, but I got - Access blocked: Debian Salsa can only be used within its organisation :(   ... and on the Debian docs I read "Your account will be locked until a gitlab administrator enables it." . I understand that spam accounts are hard to block.

**Comment by bignose-debian** [comment]
>  But for now, GitHub it's what is used by Towncrier devs and it provides tools for open colaboration.

Since neither GitHub nor GitLab provide a way to openly collaborate between repository hosts, feel free to comment here on this issue, if you have suggestions or changes for my proposed merge.

**Comment by hynek** [comment]
As Adi wrote, there's no way for us to extract a patch to apply since your repo lacks our main branch (trunk).

**Comment by bignose-debian** [comment]
> As Adi wrote, there's no way for us to extract a patch to apply

Note that there's no need to extract a patch; we're both using Git for version control, and our repositories are compatible using normal Git operations. You can bring the commits directly from another repository, no need to work with patch files.

Anyone working on this repository can [get changes from remote repositories](https://docs.github.com/en/get-started/using-git/getting-changes-from-a-remote-repository), using the normal Git distributed features.

I have now updated the branch so that it merges cleanly to the current 'trunk' branch; you can follow the above GitHub documentation, to bring those commits into your repository.
