### ISSUE TITLE
Conflicting `--version` option when using default command

### ISSUE THREAD

**Issue by SmileyChris** [twisted/towncrier#510]
Towncrier's `build` command is the default command, but it uses a custom `--version` option that collides with the base cli `--version` option that simply returns the towncrier version number.

```bash
> towncrier --version x.y --draft
towncrier, version 22.12.1.dev0
> towncrier build --version x.y --draft
[renders draft newsfile]
```

I don't really know if there's an easy out. Maybe just don't use any default command (since there's discussion about not having that as a separate dependency anyway: #506)?

**Comment by adiroiban** [comment]
I think that it works as expected

I checked a few other tools

```
$ python3 --version bla
Python 3.10.6
$ tox --version bla
3.21.4 imported from /usr/lib/python3/dist-packages/tox/__init__.py
```

We had this issue https://github.com/twisted/towncrier/issues/344
and this PR https://github.com/twisted/towncrier/pull/341


------------

Can you please specify what is the actual result and what is the expected result?

Thanks

**Comment by SmileyChris** [comment]
We have a custom `--version` option for the `build` command that is required to specify the version you're build the news for (to either override a version specified in your toml file, or if none exists this is required -- see also #507 )

https://github.com/twisted/towncrier/blob/a8f4630c126f31bf1066569406de57b00cc8bb33/src/towncrier/build.py#L81-L86

If build is the default command, it becomes partially gimped because you can't use this option when (i.e. calling `towncrier --version x.y`), as it is overridden by click's default `--version` option (returning the version number, similar to python and tox).

**Comment by adiroiban** [comment]
Thanks for the update Chris. It is still not clear what is your expected behaviour.

I think that this is the current behaviour and my expected behaviour.

* `towncrier --version ANYTHONG` just return towncrier's own version and ignore any other commands
* `towncrier build --version 1.2` - build the release notes for your project that is now at version `1.2`.

What is your expected result for these 2 commands?

**Comment by hynek** [comment]
I agree with Adi here: it's an expectation from a CLI tool to return its own version when passing `--version`. If anything by it's unfortunate that we have an version flag but it's like with e.g. `--help` and git: it applies to the active command.

**Comment by SmileyChris** [comment]
The cli doc's state that
>`build` is also assumed if no command is passed.

So I'll just put a PR for documenting that (build's) `--version` requires the `build` command to be explicitly passed.

**Comment by adiroiban** [comment]
I see... Regarding "build" implicit behavior. I think it's a best effort.

I would prefer not to have a default command... but for towncrier, I think it's too late.
So we just document the current behaviour.

And maybe in the documentation ,we can encourage people to always use an explicit command.
