### ISSUE TITLE
Automatically add links to the issues IDs

### ISSUE THREAD

**Issue by nicoddemus** [twisted/towncrier#52]
Currently towncrier only adds the issue number as text to the NEWS file, for example:

```rst
- Fix a crash on non ASCII characters from `lsb_release`. (#4062)
```

It would be nice if it automatically added a link to the issue in the repository:

```rst
- Fix a crash on non ASCII characters from `lsb_release`. (`#4062`_)

.. _#4062: https://github.com/pypa/pip/issues/4062
```

We are planning to use towncrier for [pytest's CHANGELOG](https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst) (which is maintained manually currently).

If that's acceptable I can work on a PR.

**Comment by hawkowl** [comment]
@nicoddemus I think editing the template could provide this?

**Comment by nicoddemus** [comment]
Seems like it, I was wondering though if it would be useful upstream. 

The only reason that I can see for not having this is that's non-obvious if an id belongs to an issue or PR (which changes the URL).

**Comment by adiroiban** [comment]
I am also +1 for having this in the template.

I don't know if this is possible right now as from the code I see that the ticket id is already "rendered"... see #55

**Comment by nicoddemus** [comment]
I'm not sure how much value this will bring in the end, given that adding it to the template is simple (see [here](https://github.com/pytest-dev/pytest/pull/2488/commits/536f1723acfcf81a1d6bd8b25cc107294388c841)).

**Comment by njsmith** [comment]
But aside from the general annoyingness of having to effectively fork the template file to customize this, that commit (as noted in its commit message) breaks the feature of having multiple issue numbers on the same line, and doesn't even attempt to support `showcontent=False` sections...

**Comment by mihaic** [comment]
@njsmith, the multiple issue numbers on the same line is not a problem anymore:
https://github.com/pytest-dev/pytest/commit/10ded399d8246ef8383d5cac27f58fe9b0c65fb1#diff-cd7e1bb12ed102093758ffd3721b8ede

**Comment by njsmith** [comment]
Nice. Still, I think #66 is a bit easier to use :-)

**Comment by adiroiban** [comment]
I think this can be done using the current Towncrier release in 2 ways

Option A. If you are fine with inline links, you can use the `issue_format` configuration option.

Option B. If you need links at the end of the file, create a custom template, in which the release note items are iterated twice. Once to render the text, and another one to render the RST links. 

Would that work for you?

**Comment by thet** [comment]
This issue can probably be closed.
The request is possible with `issue_format` as described here:
https://towncrier.readthedocs.io/en/stable/configuration.html

**Comment by adiroiban** [comment]
I am closing this. Thanks for the followup.
