### ISSUE TITLE
When using `towncrier create --edit`, use `.md` or `.rst`

### ISSUE THREAD

**Issue by ocharles** [twisted/towncrier#527]
Currently when I use `towncrier create --edit`, my `$EDITOR` is opened pointing at a `.txt` file. It would be better if this was actually a `.md` or `.rst` file, as my editor will then automatically enable syntax highlighting.

**Comment by adiroiban** [comment]
thanks for the report

> can you please provide more info about how to reproduce this?

What is the actual result and the expected result?

Which `$EDITOR` do you use?

This is what I get on my side, no .txt file :)

```
$ towncrier create --edit 123.feature

VI is opened, I change the file, save and exit

Created news fragment at /home/adi/chevah/towncrier/src/towncrier/newsfragments/123.feature

$ git st
?? src/towncrier/newsfragments/123.feature
```

**Comment by ocharles** [comment]
When `vim` is open are you not editing a `/tmp/foo.txt` file? That's what happens for me, using Helix. Once I'm back home I'll try and provide more details

**Comment by adiroiban** [comment]
I got it now :)
True. The file is `/tmp/editor-9c8f91am.txt` 

So, actual behaviour

```
$ towncrier create --edit 123.feature

The editor is opened with a file with a name like /tmp/editor-9c8f91am.txt
```

Expected behaviour:

```
$ towncrier create --edit 123.feature

The editor is opened with a file with a name like /tmp/editor-9c8f91am.rs
```

Happy to review a PR for this.

Not sure how to tell if you want MD or RST.

I guess that we will one more configuration option for towncrier, to specify the format if the files... this can be a separate ticket / PR.

**Comment by ocharles** [comment]
> Not sure how to tell if you want MD or RST.

I think the same way that `towncrier build` decides which format to use (which I think is by checking the extension of `filename`).

**Comment by adiroiban** [comment]
I see some work was done here https://github.com/twisted/towncrier/pull/483

True. we can use the file extension.

Instead of using .txt, use the same extension as the `filename` configuration.

Sound like a good plan :)
