### ISSUE TITLE
Document ``title_format`` and ``template``

### ISSUE THREAD

**Issue by fschulze** [twisted/towncrier#53]
The new options from #36 should either be fully documented, or at least be briefly mention. I almost didn't use towncrier because I couldn't find those options. Glad someone pointed me to a project (pip) which uses these options.

I hope to be able to make a PR, but if someone beats me to it ...

**Comment by michaeljoseph** [comment]
@fschulze #89 fixes this.

**Comment by fschulze** [comment]
Looks good, thanks!

**Comment by SmileyChris** [comment]
Documented in configuration docs
