### ISSUE TITLE
The misc type new fragment is not built into the CHANGELOG.md

### ISSUE THREAD

**Issue by drunkwcodes** [twisted/towncrier#531]
I create a misc type fragment named `8da92c49.misc.md` and have some content:

```markdown
Start to use black on May 4th. **May the force be with you.**
Also fully transition to python3, which avoids deprecated modules like cPickle, xrange etc.
```

When I used `towncrier build --draft` to preview, it only generate a file name in misc section. The content is missing.

```
### Misc

- 8da92c49
```

**Comment by hynek** [comment]
misc has `showcontent=False` by default:

https://github.com/twisted/towncrier/blob/c0af1f8940ed40d078d68564e9d0a8f7d66e6063/pyproject.toml#L104-L107

That's a feature.

**Comment by adiroiban** [comment]
Closing this since this works as expected.

The default configuration for .misc is hiding the content on purpose.

You can update the configuration to show the content for .misc

**Comment by drunkwcodes** [comment]
Thank you for the quick response.
