### ISSUE TITLE
Provide interactive prompts to create fragments with the correct names

### ISSUE THREAD

**Issue by chadrik** [twisted/towncrier#535]
As a developer, I'd like for towncrier to automatically generate the fragment file name so that I don't have to, and so that I don't make mistakes.  To achieve this, `towncrier create` should prompt the user to input the necessary info using a library like [itsprompt](https://pypi.org/project/ItsPrompt/).

The series of prompts should be:
- unique id (or press enter to use timestamp)
- fragment type
- [section](https://towncrier.readthedocs.io/en/stable/configuration.html#sections) (if they are configured)

This could be introduced in one of three ways:
- add a new flag to `towncrier create`, e.g. `towncrier create -p`
- change the default behavior of `towncrier create`
- introduce a new entrypoint, such as `towncrier new`

Take a look at the `changie new` portion of the `changie mege` animation here: https://changie.dev/guide/quick-start/

**Comment by adiroiban** [comment]
Happy to review and merge a PR for this.

I think that is ok to change the defaul behaviour of `towncrier create`

If you don't pass a `FILENAME` argument it will enter the new prompt/interactive mode.

**Comment by SmileyChris** [comment]
Implemented in #482
