### ISSUE TITLE
EncodingWarning when building

### ISSUE THREAD

**Issue by jaraco** [twisted/towncrier#561]
While building using towncrier with PYTHONWARNDEFAULTENCODING=1, I see this warning:

```
/Users/jaraco/code/jaraco/jaraco.functools/.tox/finalize/lib/python3.11/site-packages/towncrier/build.py:169: EncodingWarning: 'encoding' argument not specified
  resources.files(config.template[0]).joinpath(config.template[1]).read_text()
```

One needs to explicitly pass `encoding='utf-8'` to `.read_text()` to avoid these warnings. See [PEP 597](https://peps.python.org/pep-0597/) for details.

**Comment by adiroiban** [comment]
Thanks. Good call.

I think that `trial` is missing a helper to catch generic warnings... but maybe we can have a quick hack and run our CI with the warnings enabled and just fail somehow is a warning is raised.

But event a PR with just the explicit encoding, and without any extra warning detection, is good enough.

Happy to review a PR.
