### ISSUE TITLE
Failing to delete fragment files

### ISSUE THREAD

**Issue by MDCEY** [twisted/towncrier#60]
Everything is working exactly as expected apart from the file cleanup. I am constantly getting the following error. I simply have to delete the fragment manually, which isn't really the worst thing in the world.

> windows 7
> python 3.6.1 (virtual environment with pipenv)
> towncrier 17.4.0

```
I want to remove the following files:
C:\Users\k33k00\PycharmProjects\T-Infinity\src\t-infinity\newsfragments\vue.misc
Is it okay if I remove those files? [Y/n]: Y
fatal: pathspec 'C:\Users\k33k00\PycharmProjects\T-Infinity\src\t-infinity\newsfragments\vue.misc' did not match any files
Done!
```

I should add, even though it says the file doesn't exist, it definitely does, it even writes into the changelog

**Comment by adiroiban** [comment]
The file does not exist in the **git** tracking system :)

It does exists on disk, but on in git.

Try to do a `git add newsfragments\vue.misc` before calling towncrier and it should work.

**Comment by altendky** [comment]
@MDCEY, was adi's explanation sufficient?  Are you comfortable closing this or do you still expect something to change?  Thanks.

**Comment by adiroiban** [comment]
I think that is safe to close it. It can be reopened if required.
