### ISSUE TITLE
Don't allow multiple sections with the same path

### ISSUE THREAD

**Issue by SmileyChris** [twisted/towncrier#606]
Each section needs a unique path for towncrier to correctly pick up and build news fragments for that section.

It could be a good improvement to error out if the configuration file has multiple sections with the same path (even if that path is `""`).

**Comment by adiroiban** [comment]
Thanks for the follow up.

I think that as part of this work, we should also document the "default section" , in the configuration documentation where sections are mentioned

I can be:

* the section without a path
* if all sections have path, the first one defined is the default.
*

**Comment by SmileyChris** [comment]
Fixed
