### ISSUE TITLE
Regression/breakage on 24.7.0 - check for invalid files

### ISSUE THREAD

**Issue by aviramha** [twisted/towncrier#632]
Hi,
thanks for great project!
When we upgraded to towncrier 24.7.0, we started getting this error in CI:
```
Looking at these files:
----
1. /home/runner/work/operator/operator/Cargo.lock
2. /home/runner/work/operator/operator/changelog.d/+url-safe-fingerprint.internal.md
3. /home/runner/work/operator/operator/changelog.d/544.changed.md
4. /home/runner/work/operator/operator/THIRDPARTY.yml
5. /home/runner/work/operator/operator/Cargo.toml
6. /home/runner/work/operator/operator/CHANGELOG.md
----
Error: Invalid news fragment name: changelog_template.jinja
If this filename is deliberate, add it to 'ignore' in your configuration.
```
We have `changelog_template.jinja` set as `template` in the `towncrier.toml` config file. I realize we can add it to `ignore`, but I checked other repositories and realized we've probably followed a pattern seen in other projects, where the template is inside the changes directory - as can be seen here:

- https://github.com/pytest-dev/pytest/tree/main/changelog
- https://github.com/python-attrs/attrs/tree/main/changelog.d

I assume it's a common pattern, and will break for them. Obviously each repo can fix it by adding `ignore` but I think it'd be better to handle it on towncrier side, potentially by either deprecating the feature (showing warning saying it will fail in next versions) or releasing in major version, another option is to make towncrier ignore the file used in template automatically.

Would be happy to send a PR implementing one of the options.

Related:
https://github.com/twisted/towncrier/pull/622
https://github.com/twisted/towncrier/issues/619

**Comment by adiroiban** [comment]
Thanks for the report.

A PR to automatically ignore the template would be great.

I would be happy to review and merge and then we can trigger a new release.

Thanks again

**Comment by aviramha** [comment]
Done here - https://github.com/twisted/towncrier/pull/633

**Comment by freakboy3742** [comment]
I'm not sure this has been fixed. I'm seeing CI failures with the same error using 24.7.1:

```
Run tox -e towncrier-check
towncrier-check: install_deps> python -I -m pip install towncrier==24.7.1
towncrier-check: freeze> python -m pip freeze --all
towncrier-check: click==8.1.7,Jinja2==3.1.4,MarkupSafe==2.1.5,pip==24.1,towncrier==24.7.1
towncrier-check: commands[0]> python -m towncrier.check --compare-with origin/main
Looking at these files:
----
Error: Invalid news fragment name: template.rst
If this filename is deliberate, add it to 'ignore' in your configuration.
1. /home/runner/work/briefcase/briefcase/automation/pyproject.toml
2. /home/runner/work/briefcase/briefcase/changes/1935.misc.rst
3. /home/runner/work/briefcase/briefcase/tox.ini
4. /home/runner/work/briefcase/briefcase/pyproject.toml
----
towncrier-check: exit 1 (0.10 seconds) /home/runner/work/briefcase/briefcase> python -m towncrier.check --compare-with origin/main pid=2026
  towncrier-check: FAIL code 1 (2.43=setup[2.33]+cmd[0.10] seconds)
  evaluation failed :( (3.08 seconds)
```

* https://github.com/beeware/gbulb/actions/runs/10239027441/job/28324134923
* https://github.com/beeware/rubicon-objc/actions/runs/10238982532/job/28324041023
* https://github.com/beeware/toga-chart/actions/runs/10238980336/job/28324037142
* https://github.com/beeware/travertino/actions/runs/10238976056/job/28325827449
* https://github.com/beeware/toga/actions/runs/10238971800/job/28324020117
* https://github.com/beeware/briefcase/actions/runs/10238950647/job/28323974328

**Comment by adiroiban** [comment]
The initial PR didn't fixed the issue.

It was fixed here https://github.com/twisted/towncrier/issues/638

I will trigger a new release soon.

**Comment by freakboy3742** [comment]
> I will trigger a new release soon.

@adiroiban Are you able to give any indication when "soon" is likely to be? I have avoided introducing a workaround to my code because I was under the impression that a new point release was imminent, but if that's not the case, then a workaround may be required.

**Comment by adiroiban** [comment]
well... "soon" is as soon as someone else is requesting a new release :)

There wasn't any issue raised to request a new release.
I have created it now https://github.com/twisted/towncrier/issues/659

and the RC1 is ready for review here https://github.com/twisted/towncrier/pull/660
