### ISSUE TITLE
Add `.gitkeep` as one of default valid filenames

### ISSUE THREAD

**Issue by stevepiercy** [twisted/towncrier#643]
With the change from https://github.com/twisted/towncrier/pull/622, a [very common filename `.gitkeep`](https://github.com/search?q=gitkeep&type=code) was omitted from the list of valid filenames.

Would you please consider adding the filename `.gitkeep` to the list at https://github.com/MetRonnie/towncrier/blob/9b685033b22bd3ee1bd81955a333e0e20bef02e6/src/towncrier/_builder.py#L117?

I would be happy to submit a PR to save myself several hours of work to modify our repositories in the Plone organization alone.

Thank you for your consideration.

Ref https://github.com/plone/volto/issues/6225

**Comment by adiroiban** [comment]
Thanks for report.

Yes. I would be happy to have it to the list.

**Comment by stevepiercy** [comment]
@adiroiban PR added: https://github.com/twisted/towncrier/pull/647. Thank you!
