### ISSUE TITLE
template file not ignored in `towncrier check`

### ISSUE THREAD

**Issue by rogersheu** [twisted/towncrier#658]
I was working on a PR in `pylint` at https://github.com/pylint-dev/pylint/pull/9868 and was encountering the error in [this action](https://github.com/pylint-dev/pylint/actions/runs/10434516223/job/28899884764?pr=9868), which has the line:

```
Error: Invalid news fragment name: _template.rst
```

We could theoretically just add a line to the `towncrier.toml` saying `ignore = ["_template.rst"]`, but this particular file is already being assigned as the template in that toml with `template = "doc/whatsnew/fragments/_template.rst"`, and if the template file is already being identified, it doesn't seem in the spirit of towncrier to have to add in that template path (or file name) to the ignore list.

I'm not sure exactly what changed between 23.11 and 24.7, which it seems like occurred around 2 weeks ago, but my guess is that it was working as expected beforehand and some change led it to regress.

I suspect this issue might be somewhat similar to #641, though it's also different because this implementation does not use `--dir`.

**Comment by jacobtylerwalls** [comment]
I think the update is here: https://github.com/twisted/towncrier/issues/632#issuecomment-2268618160.

**Comment by rogersheu** [comment]
I see. It looks like #639 will fix this issue, but it hasn't been included in a release cut yet.

Thanks @jacobtylerwalls !
