### ISSUE TITLE
Restore documentation to source manifest

### ISSUE THREAD

**Issue by bignose-debian** [twisted/towncrier#672]
Please restore the documentation source, to the source manifest (so that it is included in the Python sdist).

In commit 6463b5a8601957a40ee83aaf12fcad9e5a25d458 a `recursive-exclude` was added to the 'Manifest.in' file, deliberately excluding the documentation source from the sdist.

That commit has no explanation for the change; the commit message in its entirety is "fixes".

Please revert that change, and include the documentation in the sdist as before.

**Comment by adiroiban** [comment]
It looks like this change was done as part of this PR https://github.com/twisted/towncrier/pull/368

--------

I am not sure what is requested here.

Why do we need the documentation source for the Python sdist package ?

The documentation source is designed to be used by the Read The Docs service.

-------

Is this about the `man` documentation ?

I think that the idea was to use `click-man towncrier` to generate a man file for towncrier.

We might want to add some info in our README or docs to help distribute `towncrier` in various formats.


We already have the docmentation for the CLI duplicated in ReStructuredTest and Click Help format.
I would like not to have it replicated again as man `format`

In an ideal case, the CLI documentation is only defined in `click`

From `click` we can take the documentation and generate RST or man versions.

**Comment by bignose-debian** [comment]
@adiroiban wrote:
> I am not sure what is requested here.

The request is for [Source Distribution](https://packaging.python.org/en/latest/flow/#the-source-distribution-sdist) to include what is needed for building the package for local installation:

> A source distribution contains enough to install the package from source in an end user’s Python environment. As such, it needs the package source, and may also include tests and documentation. These are useful for end users wanting to develop your sources […]

That was already happening, and this request is to restore the documentation source by [updating the Source Manifest to include it](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html#using-manifest-in).

@adiroiban wrote:
> Why do we need the documentation source for the Python sdist package ?

Because the documentation source is part of the source for this project, and is needed to change and build that documentation. The Source Distribution allows access to this source without needing further network access; and having the documentation build and installed locally allows accessing it without requiring network.

> The documentation source is designed to be used by the Read The Docs service.

I hope you can appreciate that programs should not be unnecessarily dependent on network access merely to read their documentation. Distributing the documentation source as part of the Source Distribution ensures that standard way of building the entire package from distributed source, as described in the Python Packaging Guide quoted above.

> Is this about the `man` documentation ?

All the documentation that you consider part of this project, yes. Please ensure it is part of the Source Distribution, by restoring its source to the source manifest.

**Comment by adiroiban** [comment]
Thanks Ben for the information. I appreciate all the hard work done by the Debian project.

I have created https://github.com/twisted/towncrier/pull/673 to fix this

This is ready for review.

I hope all is ok and we can merge it soon.
