### ISSUE TITLE
add ability for towncrier's check to included staged files as part of its comparison against another branch

### ISSUE THREAD

**Issue by krpatter-intc** [twisted/towncrier#676]
To enable using towncrier as a pre-commit hook (vs. a post-commit hook) it would be helpful if the `towncrier check` command included staged files as part of its comparison

This is a follow on to: https://github.com/twisted/towncrier/issues/600#issuecomment-2515722908

**Comment by adiroiban** [comment]
Fixed by https://github.com/twisted/towncrier/pull/677
