### ISSUE TITLE
Supported languages?

### ISSUE THREAD

**Issue by htgoebel** [twisted/towncrier#82]
The readme says:
> towncrier, as a command line tool, works on Python 2.7/3.3/3.4/3.5 only

Does this mean, the towncrier requires one of these Python-versions to work (say: is compatible with these)? Or does this mean towndcrier is analyzing the project's source files in some way and for this supports Python but not e.g. Ruby?

**Comment by hawkowl** [comment]
Towncrier will use Incremental (https://github.com/twisted/incremental), or a `__version__` in the package's top level, if it's Python. But you can pass `--version` to towncrier to bypass this check, if you don't use Python. I'll have to make this clearer.

**Comment by hynek** [comment]
this is now clarified in the readme / front page:
<img width="809" alt="CleanShot 2022-12-05 at 06 58 25@2x" src="https://user-images.githubusercontent.com/41240/205560266-bd64d527-3da1-4ef4-9da4-2f406a4cc52e.png">
