### ISSUE TITLE
Questions about the readme

### ISSUE THREAD

**Issue by htgoebel** [twisted/towncrier#83]
The readme is not clear for me. Beside answering my questions here, maybe you want to put the answers into the readme.
- Why is package_dir and package needed? If my package does not reside in sub-folder, is package_dir to be set, too, and to which value?
- Are several packages in one repo supported (distutils support this)?
- Why do I need to specify the package at all? Is is used for getting the version only?
- Why should git be prevented from removing the newsfragments directory?
- How does "produce the news file for real" differ from "draft"?
- "pyproject.toml" or "towncrier.ini"?

**Comment by hawkowl** [comment]
I do need to rewrite these docs properly, I'll take these points into consideration when I do it, thanks!

**Comment by michaeljoseph** [comment]
Hi @htgoebel, I think #89 answers some of your questions...

**Comment by adiroiban** [comment]
We now have documentation on RTD.

If anything is not clear on the RTD page, please let use know.

I am closing this for now.
