### ISSUE TITLE
Make path to newsfragments directory configurable

### ISSUE THREAD

**Issue by htgoebel** [twisted/towncrier#87]
IMHO *package_dir*/*package*/newsfragments is no a good place. I would like to have it under `docs/newsframents`, other may want to have it somewhere else.

Please add a config option to specify the path of this directory.

**Comment by hynek** [comment]
That’s configurable but currently a bunch of options aren’t documented yet.  `attrs` uses a bunch of them, maybe you want to have a look:

https://github.com/python-attrs/attrs/blob/0d04d5e7fc6de9eb6d70839dfda994d2a4bfa80f/pyproject.toml#L1-L8

**Comment by michaeljoseph** [comment]
#89 fixes this.

**Comment by dklimpel** [comment]
IMO this can be closed.
